# Generated by Django 4.0.2 on 2023-04-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Property Dealer', 'Property Dealer')], default='Customer', max_length=20),
        ),
    ]
